nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: []
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
        allow_headers: []
        expose_headers: []
        max_age: 0
    paths:
        '^/api/': 
          origin_regex: true
          allow_origin: ['*']
          allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
          allow_headers: ['*']
          max_age: 3600
